Home/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  9 18:19:42 2023

@author: KeithLee
"""

from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

# 主頁
urlpatterns = [
    path('', views.index, name='index'),
    path('recommend/', views.coffee_stores, name='recommend'), # 推薦頁面
    path('aboutus/', views.AboutUs, name='abountus'), # 關於我們
    ]


from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

# 帳號
urlpatterns += [
    path('signup/', views.signup, name='signup'), # 註冊
    path('myaccount/', views.myaccount, name='myaccount'), # 我的帳號
    path('myaccount/edit/', views.edit_myaccount, name='edit_myaccount'), # 帳號資料編輯
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'), # 登入
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), # 登出
    
    path('password_reset/',
         views.PasswordResetView.as_view(template_name='account/password_reset_form.html'), 
         name='password_reset'), # 填寫重設密碼信箱
    
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), 
         name='password_reset_done'), # 填寫完顯示已發送信件字體
    
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', success_url=reverse_lazy('password_reset_complete')), 
         name='password_reset_confirm'), # 從後台得到連結後重設密碼的頁面
    
    path('reset/done/', 
         PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), 
         name='password_reset_complete'), # 完成密碼重置並顯示再次登入連結
    ]

keithcoffee/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf.urls import include
from . import settings



urlpatterns = [
    path('admin/', admin.site.urls),
]

# 主頁路徑
urlpatterns += [
    path('Home/', include('Home.urls')),
    path('', RedirectView.as_view(url='Home/')), # 當網址空白時 重定向到主頁
    ]

# 產品路徑
urlpatterns += [
    path('products/', include('product.urls'), name='product'),
    ]

# 購物車路徑
urlpatterns += [
    path('cart/', include('cart.urls'), name='cart'),
    ]

# API
urlpatterns += [
    path('api/', include('myapi.urls'), name='myapi'),
    ]

# 第三方工具silk
if settings.DEBUG:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

# django-debug-toolbar 路徑設置
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# 配置圖片讀取路徑
from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  9 23:34:50 2023

@author: KeithLee
"""

from django.urls import path
from django.views.generic import RedirectView
from . import views
    
urlpatterns = [
    path('', RedirectView.as_view(url='all-product/')), # 讓空格重新導向
    path('all-product/', views.ProductsView.as_view(), name='all-product'), # 所有產品頁面
    path('new-product/', views.NewProductsView.as_view(), name='new-product'), # 最新產品頁面
    path('<str:category>/', views.ProductCategoryView.as_view(), name='product-category'), # 類別產品頁面
    path('all-product/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'), # 產品細節頁面
    ]

product/models.py
from django.db import models


# 產品類別資料庫
class Category(models.Model):
    name = models.CharField(verbose_name='商品種類英文簡稱', max_length=10)
    category_name = models.CharField('商品中文名', null=True, blank=True, max_length=30)
    
    def __str__(self):
        return self.category_name


# 產品資料庫
from decimal import Decimal
from django.urls import reverse

class Product(models.Model):
    name = models.CharField('商品名稱', max_length=100)
    product_inst = models.CharField('簡介', max_length=30, help_text='請輸入產品簡介，限定30個字。')
    product_desc = models.TextField('描述', max_length=1000, help_text='請輸入產品詳細敘述，限定1000個字。')
    image = models.ImageField(upload_to='product_image/')
    price = models.DecimalField('價格', max_digits=10, decimal_places=0)
    code = models.CharField('編號', max_length=10, blank=True, null=True,help_text='可自訂，也可根據類別自動生成編碼')
    category = models.ForeignKey(Category, 
                                 related_name='products', 
                                 verbose_name='商品種類',
                                 on_delete=models.SET_NULL, 
                                 null=True
                                 )
    
    date_of_create = models.DateField('創建日期', auto_now_add=True)
    date_of_update = models.DateField('修改日期',auto_now=True)
    
    SHELVS_STATUS = (
        ('o', '上架'),
        ('u', '下架'),
        )    
    
    status = models.CharField(
        verbose_name='上架狀態',
        max_length=1,
        choices=SHELVS_STATUS,
        blank=True,
        default='o',
        help_text='架上狀態',
        )
    
    class Meta:
        ordering = ['-date_of_create']
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])
    
    def query_set(self):
        return self.id

    # 定義折扣價格
    @property
    def on_sale(self):
        return round((self.price * Decimal('0.9')), 0)
    
    
# 保存產品編碼信號設定
from django.db import models # 用於定義資料模型
# 導入Django的post_save信號，用於在模型實例保存後發送信號
from django.db.models.signals import post_save
# 導入receiver裝飾器，它用於將信號處理函數與信號關聯 
from django.dispatch import receiver

"""
信號處理函數，用於生成和保存code
sender：發送信號的模型。
instance：接收信號的模型的實例。
created：一個布林值，指示是否正在創建新的實例。
**kwargs：是用於接收其他可能的關鍵字參數的字典。
"""
@receiver(post_save, sender=Product)
def generate_product_code(sender, instance, created, **kwargs):
    if created and not instance.code:  # 只在對象創建時運行，確保code字段為空
        product_code = f"{instance.category} - {instance.id:04d}"
        instance.code = product_code
        instance.save() # 保存生成的code回數據庫

        
    
# 產品子類別資料庫
class ProductVariant(models.Model):
    product = models.ForeignKey(Product, related_name='variants', verbose_name='產品' , on_delete=models.CASCADE)
    size = models.CharField('產品變量', max_length=20, null=True, blank=True) # 產品尺寸

    date_of_create = models.DateField(auto_now_add=True) # 新增時間
    date_of_update = models.DateField(auto_now=True) # 更新時間
    

    class Meta:
        ordering = ['date_of_create'] 
    
    
    def __str__(self):
        return self.product.name

    @property
    def pound(self):
        return round((self.price * Decimal('0.9') * 2), 0)

product/views.py
from .models import Product, Category
from django.views import generic

# 所有產品顯示頁面
class ProductsView(generic.ListView):
    model = Product
    paginate_by = 12
    
    def get_queryset(self):
        searchp = self.request.GET.get('searchp', '')
        sort_option = self.request.GET.get('sort_option', '')
        
        if searchp:
            queryset = Product.objects.filter(name__icontains=searchp, status__exact='o')
        else:
            queryset = Product.objects.filter(status__exact='o')
    
        if sort_option == 'new':
            queryset = queryset.order_by('-date_of_create')
        elif sort_option == 'ud':
            queryset = queryset.order_by('-price')
        elif sort_option == 'du':
            queryset = queryset.order_by('price')
            
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['searchp'] = self.request.GET.get('searchp', '')
        context['sort_option'] = self.request.GET.get('sort_option', '')

        return context

        
# 產品各種類別顯示頁面
class ProductCategoryView(generic.ListView):
    model = Product
    paginator_by = 12
    template_name = 'product/product_category_list.html'
    
    # 用來處理資料集
    def get_queryset(self):
        category_n = self.kwargs.get('category') # 取得category參數
        # 取得category裡面的name資料，不能用Product尋找，因為Product只找的到字段。
        category = Category.objects.get(name=category_n)
        if category:
           queryset = Product.objects.filter(category=category, status__exact='o')     
        
        searchp = self.request.GET.get('searchp', '')
        sort_option = self.request.GET.get('sort_option', '')            

        if searchp:
            queryset = queryset.filter(name__icontains=searchp)
    
        if sort_option == 'new':
            queryset = queryset.order_by('-date_of_create')
        elif sort_option == 'ud':
            queryset = queryset.order_by('-price')
        elif sort_option == 'du':
            queryset = queryset.order_by('price')
        
        return queryset
    
    # 用來傳遞資訊到HTML
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_n'] = self.kwargs.get('category')
        context['searchp'] = self.request.GET.get('searchp', '')
        context['sort_option'] = self.request.GET.get('sort_option', '')

        return context


# 最新產品顯示頁面
class NewProductsView(generic.ListView):
    mdoel = Product
    template_name = 'product/product_new_list.html'
    
    # 無法在最新產品頁面內用切片搜尋完的產品資料再去做條件搜尋。
    def get_queryset(self):
        searchp = self.request.GET.get('searchp', '')
        sort_option = self.request.GET.get('sort_option', '')   
        queryset = Product.objects.filter(status__exact='o')
        if searchp:
            # 如果搜尋參數存在，過濾查詢集合。
            queryset = queryset.filter(name__icontains=searchp)
    
        if sort_option == 'new':
            # 根據排序參數排序
            queryset = queryset.order_by('-date_of_create')[:12]
        elif sort_option == 'ud':
            queryset = queryset.order_by('-price', '-date_of_create')[:12]
        elif sort_option == 'du':
            queryset = queryset.order_by('price', '-date_of_create')[:12]
        else:
            queryset = queryset.order_by('-date_of_create')[:12]
        
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['searchp'] = self.request.GET.get('searchp', '')
        context['sort_option'] = self.request.GET.get('sort_option', '')
        return context


# 產品detail顯示頁面
class ProductDetailView(generic.DetailView):
    model = Product
    def get_queryset(self):
            
        return Product.objects.filter(status__exact='o')
    

product/templates/product/product_category_list.html
{% extends 'product_Base.html' %}

{% load humanize %}

{% block title %}
    {{ category_n }}
{% endblock %}

{% block page_name %}
    {{ category_n }}
{% endblock %}



{% block content %}


{% for product in product_list %}
    <div class="col" style="width: 220px; margin: 10px; display: flex; flex-direction: column; justify-content: space-between;">
        <!-- 產品 -->
        <div class="col" style="width: 200px; ">
            <a href="{{ product.get_absolute_url }}" style="text-decoration: none;">
                <div class="card shadow-sm">
                    <div>
                        <img src="{{ MEDIA_URL }}{{ product.image }}" alt="Image" class="img-fluid" style="border-radius: 0.35em 0.35em 0 0;">
                    </div>
                    <div class="card-body">
                        <div style="width: 100%; padding-bottom: 10px;">
                            <p class="card-text" style="text-align: center; font-weight: bold;">
                            	<!-- 產品名稱 -->
                            	<small class="text-body-secondary" style="font-size: 16px;">{{ product.name }}</small>
                			</p>
                        </div>
                        <div class="justify-content-between align-items-center" style="padding: 10px 10px 10px 10px;">
                    		<!-- 價格 -->
                            <span class="card-text h5" style="margin-left: 5px;">
                                <span style="margin-right: 10px; color: #999; font-size: 12px;">
                                    <del>NT{{ product.price|intcomma }}</del> 
                                </span>
                                <span style="color: #999;">
                                    NT{{ product.on_sale|intcomma  }}
                                </span>
                            </span>     	                	
                        </div>
            		</div>
                </div>
            </a>
        </div>
    </div>
{% endfor %}

{% endblock %}

product/templates/product/product_detail.html
{% extends 'product_Base.html' %}

{% load humanize %}

{% block title %}{{ product.name }}{% endblock %}

<!-- 產品名稱顯示 -->
{% block page_name %} {{ product.name }} {% endblock %}


{% block content %}

    <!-- 移除掉產品上源線 -->
    {% block underline %}
    {% endblock %}
    <!-- 產品細節搜尋欄 -->
    {% block search_product %}
    {% endblock %}

    <div class="main">
        <div class="h-100 p-5 bg-body-tertiary border rounded-3" style="width: 930px; margin: 5px;">
                <!-- 產品圖片 -->
                <img src="{{ MEDIA_URL }}{{ product.image }}" alt="" style="width: 400px;">
            
            <div class="productDetails" style="float: right; padding-right: 10px; width: 400px;" >
                <div style="padding: 0px 20px 20px 20px;">
                    <div class="proLabel">                    
                        <figure>
                            <blockquote class="blockquote">
                                <!-- 產品名稱 -->
                                <span class="opacity-75" style="font-size: 23px; letter-spacing: 2px;">{{ product.name }}</span>
                            </blockquote>
                            <figcaption class="blockquote-footer" style="">
                                <!-- 產品貨號 -->
                                <cite title="Source Title" style="margin-left: 5px;">
                                {{ product.code }}
                                </cite>
                            </figcaption>
                        </figure>                                    
                    </div>

                    <hr style="opacity: .2;" />
                    <div style="padding: 0.5em;">
                        <!-- 產品價格 -->
                        <span class="opacity-75" style="color: #E7412C; font-size: 28px; letter-spacing: 3px;" id="product-price">NT{{ product.on_sale|intcomma }}</span>
                    </div>
                    <hr style="opacity: .2;" />

                    <div style="padding: 0.3em;">
                        <span class="opacity-75" style="color: #E7412C; font-size: 16px; letter-spacing: 3px;" id="product-price">咖啡豆價格顯示已半磅為主。選擇對應的產品填加入購物車，數量請在購物車裡更改。</span>
                    </div>
                    <hr style="opacity: .2; clear: both;" />

                    {% for variant_p in product.variants.all %}
                        <div style="padding: 10px; display: flex; align-items: center;">
                            <span style="padding-right: 20px;">SIZE : </span>
                            <!-- 品項選擇 -->                   
                            <button class="btn btn-outline-secondary size-button" data-size="{{ variant_p.size.id }}" type="button" style="margin-right: 15px; height: 40px; font-size: .575em; font-style: italic; width: 80px;">
                            {{ variant_p.size }}
                            </button>      
                            <!-- 加入購物車按鈕 -->
                            <a href="#"
                                hx-get="{% url 'add_to_cart' variant_p.id %}"
                                hx-target="#menu-cart-button"
                                hx-swap="outerHTML"
                            >
                                <button id="add_cart" class="btn btn-outline-secondary add-to-cart" type="button" style="width:150px; height: 40px; background-color: #212529; margin-left: 10px;">
                                    <strong style="color: #DEE2E6; font-size: 16px;">加入購物車</strong>
                                </button>
                            </a>                                                      
                        </div>                              
                    {% endfor %}

                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="h-100 p-5 bg-body-tertiary rounded-3" style="width: 930px; margin: 20px 5px 5px 5px;">
                <figure>
                    <blockquote class="blockquote">
                        <h1 class="class="display-5">簡介</h1>
                    </blockquote>
                    <figcaption class="blockquote-footer" style="">
                        <cite title="Source Title" style="margin-left: 5px;">
                        <!-- 產品名稱 -->
                        Product Introduction
                        </cite>
                    </figcaption>
                </figure>
                <p class="white-space:pre-wrap" style="line-height: 200%; letter-spacing: 2px;">
                    <!-- 產品簡介 -->
                    {{ product.product_inst }}
                </p>

            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-5 bg-body-tertiary border rounded-3" style="width: 930px; margin: 20px 5px 5px 5px;">
                <figure>
                    <blockquote class="blockquote">
                        <h1 class="class="display-5">產品介紹</h1>
                    </blockquote>
                    <figcaption class="blockquote-footer" style="">
                        <cite title="Source Title" style="margin-left: 5px;">
                        Product Presentation
                        </cite>
                    </figcaption>
                </figure>
                <!-- 產品描述 -->
                <p class="white-space:pre-wrap" style="line-height: 200%; letter-spacing: 2px;"> 
                    {{ product.product_desc }}
                </p>

            </div>
        </div>
    </div>


{% endblock %}

product/templates/product/product_list.html
{% extends 'product_Base.html' %}

{% load humanize %}

{% block title %}所有商品{% endblock %}

{% block page_name %}所有商品{% endblock %}

{% block content %}

{% for product in product_list %}
    <div class="col" style="width: 220px; margin: 10px; display: flex; flex-direction: column; justify-content: space-between;">
        <!-- 產品 -->
        <div class="col" style="width: 200px; ">
            <a href="{{ product.get_absolute_url }}" style="text-decoration: none;">
                <div class="card shadow-sm">
                    <div>
                        <img src="{{ MEDIA_URL }}{{ product.image }}" alt="Image" class="img-fluid" style="border-radius: 0.35em 0.35em 0 0;">
                    </div>
                    <div class="card-body">
                        <div style="width: 100%; padding-bottom: 10px;">
                            <p class="card-text" style="text-align: center; font-weight: bold;">
                            	<!-- 產品名稱 -->
                            	<small class="text-body-secondary" style="font-size: 16px;">{{ product.name }}</small>
                			</p>
                        </div>
                        <div class="justify-content-between align-items-center" style="padding: 10px 10px 10px 10px;">
                    		<!-- 價格 -->
                        	<span class="card-text h5" style="margin-left: 5px;">
                        		<span style="margin-right: 10px; color: #999; font-size: 12px;">
                        			<del>NT{{ product.price|intcomma }}</del> 
                        		</span>
                        		<span style="color: #999;">
                                    NT{{ product.on_sale|intcomma  }}
                                </span>
                        	</span>				                	
                        </div>
            		</div>
                </div>
            </a>    
        </div>
    </div>
{% endfor %}

{% endblock %}

product/templates/product/product_new_list.html
{% extends 'product_Base.html' %}

{% load humanize %}

{% block title %}最新商品{% endblock %}

{% block page_name %}最新商品{% endblock %}


{% block content %}

{% for product in product_list %}
    <div class="col" style="width: 220px; margin: 10px; display: flex; flex-direction: column; justify-content: space-between;">
        <!-- 產品 -->
        <div class="col" style="width: 200px; ">
            <a href="{{ product.get_absolute_url }}" style="text-decoration: none;">
                <div class="card shadow-sm">
                    <div>
                        <img src="{{ MEDIA_URL }}{{ product.image }}" alt="Image" class="img-fluid" style="border-radius: 0.35em 0.35em 0 0;">
                    </div>
                    <div class="card-body">
                        <div style="width: 100%; padding-bottom: 10px;">
                            <p class="card-text" style="text-align: center; font-weight: bold;">
                            	<!-- 產品名稱 -->
                            	<small class="text-body-secondary" style="font-size: 16px;">{{ product.name }}</small>
                			</p>
                        </div>
                        <div class="justify-content-between align-items-center" style="padding: 10px 10px 10px 10px;">
                    		<!-- 價格 -->
                            <span class="card-text h5" style="margin-left: 5px;">
                                <span style="margin-right: 10px; color: #999; font-size: 12px;">
                                    <del>NT{{ product.price|intcomma }}</del> 
                                </span>
                                <span style="color: #999;">
                                    NT{{ product.on_sale|intcomma  }}
                                </span>
                            </span>                    	
                        </div>
            		</div>
                </div>
            </a>
        </div>
    </div>
{% endfor %}

{% endblock %}